#!/bin/bash

# Get the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

if [[ -n "$pid" ]]; then
    echo "Stopping 7-highlander (PID: $pid)"
    kill "$pid"
else
    echo "Process 7-highlander is not running."
fi
